### ISSUE TITLE
购买hostmonster独立IP

### ISSUE THREAD

**Issue by yihui** [cosname/admin#11]
没办法，要对付墙

**Comment by nanxstats** [comment]
ĿǰǶIP

2011/3/28 yihui <
reply@reply.github.com>

> û취ҪԸǽ
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/cosname/admin/issues/11

## 

Best Regards,

## Xiao Nan

Xiao Nan road2stat@gmail.com
Homepage: http://road2stat.com/
Dept. of Stat., School of Math. Sci. & Comp Tech.,
Central South University, Changsha, 410075, China

**Comment by yihui** [comment]
乱码？

**Comment by yanping** [comment]
如何加到cosname 这个账户里？

**Comment by yihui** [comment]
已加。
