### ISSUE TITLE
新站预览测试站

### ISSUE THREAD

**Issue by Gwill** [cosname/admin#13]
Hi all,

今天把新站部署到以前用的一个稳定的空间上了，不用再受亚马逊启动变域名的困扰了。
现在已经开始调整所有的前端页面样式了。

http://cos.statsnews.org/

大家有什么问题，尽快反馈。

**Comment by Gwill** [comment]
测试账号：

test@test.com
test

**Comment by mingsnu** [comment]
模板还要换么？logo和模板的色调不一致。

**Comment by Gwill** [comment]
@mingsnu 新站这个版本不换了。因为整体配色还是很难，我试了下发现怎么弄都不好看。现在的配色是直接取自 Flat-UI （ http://designmodo.github.io/Flat-UI/ ） 的配色，没有做改动。和现在的 logo 搭配，logo 反而有突出的感觉，整体上感觉是不错的。

**Comment by joegaotao** [comment]
挺好的。文章那一页面下还需要分很多主题吧？

**Comment by Gwill** [comment]
@joegaotao 主题是指 wordpress里分类（ category ）的概念吗？ 现在的思路是不做分类，只记标签。感觉分类意义不大，因为很多文章很难归类，如果按照wordpress的思路就是单文章可以属于多分类，这事实上就和标签的作用冲突了，所以设计的时候考虑舍弃分类，只做标签。

**Comment by joegaotao** [comment]
这样不太好吧。标签会有大小之分么？分类和标签的效果不太一样。一般统计的文章归类还是比较好归的。我还想的是有一个页面可以专门提供R的基础材料和进阶材料，免去很多人自己去搜集的痛苦。

**Comment by Gwill** [comment]
标签都是同级的。关于分类，我再去看看别人是怎么做的，我想，如果要分类的话，也应该是一篇文章属于一个分类，如果像 wordpress 那样多对多的分类，感觉不合理。

专门提供R的基础材料和进阶材料的页面，可以作为单独的一篇文章，然后在侧栏之类的位置单独给出链接，作为提醒与加强。

**Comment by joegaotao** [comment]
单独的文章我觉得可能不够的。不是专门的科普的文章。可以将一硕之前写那种R学习路线图加强点，然后给出相应的路线文章。像以前思喆写的R的153分钟、后面还有相关的资料都可以的。甚至我建议R忍者秘籍可以开放出来，只要有兴趣的都可以往里面加。将之前的章节一点一点的放出来，做好知识产权保护：）社区网站嘛，多分享。相关学习资料后面，都可以写明捐赠的话语。加强捐赠:)

**Comment by nanxstats** [comment]
咳咳，设置 - 个人资料 - 头衔 和 个人简介 两个地方有存储型 XSS，测试效果：

http://cos.statsnews.org/user/1

刚才又在 新闻投递 那里随便投了一两个，报了这个错，然后再登录就一直是这个页面了 ……

<img src='http://i.imgur.com/y9vall8.png' />

**Comment by joegaotao** [comment]
现在貌似真没法用了~

**Comment by Gwill** [comment]
现在好了。

---

@road2stat  嗯，跨站都还没有处理。

下面那个是因为 tag 有非法输入。

搞安全的人太生猛了。

太好了，这下子连安全审查都就位了。

P.S. 有漏洞下手轻一点，共享空间估计SA会严一点，要是被封掉，就小麻烦了。

P.S. 评论那块感觉跨站风险更大， @road2stat 可以多看一下。

**Comment by Gwill** [comment]
@joegaotao 就是说将“R的基础材料和进阶材料”看做大分类，里面的元素还是由文章组成？那么这样来看，分类是有必要的，那么就实现一个，一篇文章只属于一个分类，分类分父子的这样一个分类架构。我去折腾。

**Comment by nanxstats** [comment]
@Gwill 都懂得。

创建小组那里也能跨，看来用户能 POST 的地方可能都需要过滤下。

评论和发文不是用的成熟的中间件？应该自带了过滤吧？

上传的处理需要比较小心，似乎还没做上去，不过这块是最危险的。

**Comment by Gwill** [comment]
明白了，我去处理。

另外：

访问 http://cos.statsnews.org/schema/down 是销毁所有表。

访问 http://cos.statsnews.org/schema/up 是建立所有表。

要是玩的不能访问了，就执行以下销毁和建立。

**Comment by joegaotao** [comment]
@Gwill 是的呀。一个大类。目前这些类迁移估计会有些麻烦。从主站那边，确实很多文章是多对一的。建议父子成树状。可以分属与几个小类

**Comment by Gwill** [comment]
@joegaotao  关于文章部分的迁移，当时设计的时候有考虑，因为 wordpress 导出功能很强大，所以迁移问题不大，再准备点脚本就更舒服了。文章分类加入 todo ，着手去做。

**Comment by yihui** [comment]
又撤下了么？Under Maintenance

**Comment by Gwill** [comment]
嗯，改了一些代码。等会再去把代码上传上去。

先把这个issue关掉。

**Comment by joegaotao** [comment]
不知现在新站如何了啊？

感觉这个网站的分块结构很好，http://www.cfcity.cn/
和我预期的很像诶。主文章、精选、分类阅读、博客聚合。当然如果新站已经好了就OK了呀:)

On Mon, Jun 24, 2013 at 2:20 PM, G_will notifications@github.com wrote:

> 嗯，改了一些代码。等会再去把代码上传上去。
> 
> 先把这个issue关掉。
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cosname/admin/issues/13#issuecomment-19890791
> .

## 

Best Regards,

## Tao Gao

Tao Gaojoegaotao@gmail.com
Homepage<http://www.gaotao.name <http://gaotao.name/>>
School of Statistics,Renmin University of China

**Comment by dengyishuo** [comment]
OK。界面很不错，你是怎么翻到金融城这个网站的？

## 

---

微博（weibo）：http://weibo.com/dengyishuo
博客（Blog）：http://yishuo.org

## 微信（weixin）：dengyishuo

If you want to improve, be content to be thought foolish and stupid.

## 择善固执，纵望之愚且鲁，何足介怀？

在 2013-09-05 00:37:28，"Gao Tao" notifications@github.com 写道：
不知现在新站如何了啊？

感觉这个网站的分块结构很好，http://www.cfcity.cn/
和我预期的很像诶。主文章、精选、分类阅读、博客聚合。当然如果新站已经好了就OK了呀:)

On Mon, Jun 24, 2013 at 2:20 PM, G_will notifications@github.com wrote:

> 嗯，改了一些代码。等会再去把代码上传上去。
> 
> 先把这个issue关掉。
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cosname/admin/issues/13#issuecomment-19890791
> .

## 

Best Regards,

## Tao Gao

Tao Gaojoegaotao@gmail.com
Homepage<http://www.gaotao.name <http://gaotao.name/>>
School of Statistics,Renmin University of China

**Comment by joegaotao** [comment]
昨晚你的微博啊：）

在 2013-9-5，8:35，邓一硕 notifications@github.com 写道：

> OK。界面很不错，你是怎么翻到金融城这个网站的？
> 
> ## 
> 
> ---
> 
> 微博（weibo）：http://weibo.com/dengyishuo
> 博客（Blog）：http://yishuo.org
> 
> ## 微信（weixin）：dengyishuo
> 
> If you want to improve, be content to be thought foolish and stupid.
> 
> ## 择善固执，纵望之愚且鲁，何足介怀？
> 
> 在 2013-09-05 00:37:28，"Gao Tao" notifications@github.com 写道：
> 不知现在新站如何了啊？
> 
> 感觉这个网站的分块结构很好，http://www.cfcity.cn/
> 和我预期的很像诶。主文章、精选、分类阅读、博客聚合。当然如果新站已经好了就OK了呀:)
>

**Comment by Gwill** [comment]
不好意思，最近工作很忙，很多事情自己搞不定只能靠时间磨，说多了都是泪。

**Comment by dengyishuo** [comment]
郭巨侠辛苦了！注意身体！李开复的事情让我觉得IT从业人员要以健康为重。

## 

---

微博（weibo）：http://weibo.com/dengyishuo
博客（Blog）：http://yishuo.org

## 微信（weixin）：dengyishuo

If you want to improve, be content to be thought foolish and stupid.

## 择善固执，纵望之愚且鲁，何足介怀？

在 2013-09-10 13:01:39，G_will notifications@github.com 写道：

不好意思，最近工作很忙，很多事情自己搞不定只能靠时间磨，说多了都是泪。

**Comment by joegaotao** [comment]
是啊。。没关系，现在主站能跑得起来：）多运动吃水果：）

在 2013-9-10，15:38，邓一硕 notifications@github.com 写道：
