### ISSUE TITLE
建议为评论添加 oo xx 功能

### ISSUE THREAD

**Issue by nanxstats** [cosname/admin#14]
可以支持或者反对评论，增强互动。

或者为了和谐，只设 oo 不设 xx。

**Comment by Gwill** [comment]
这个不错。

项目在这里： https://github.com/Gwill/distribution/ ，具体的 issue 可以发到那边。

关于评论顶踩，当时对于文章模块想的就是能和现在主站 wordpress 表现的差不多就好，所以细节功能都没细想。思路在这里： https://github.com/cosname/admin/blob/master/CEP/cep-002.md 。 我看了下果壳，这样确实比较有意思，加入 todo 。
