### ISSUE TITLE
在线统计分析系统？

### ISSUE THREAD

**Issue by yihui** [cosname/admin#3]
可否设计一个在线Sweave报告？比如先做一些简单模块如回归。

http://bayes.math.montana.edu/Rweb/Rweb.general.html

http://rweb.stat.ucla.edu/ggplot2/

http://yihui.name/cn/2010/04/stat-computation-math-logic/

**Comment by yihui** [comment]
yixuan December 09, 2010 | link | edit | delete

一个之前设计过的在线分析系统，后来没时间去维护，就一直搁在那儿。 http://blog.applstats.org/webR

yihui December 10, 2010 | link | edit | delete

不错不错。

这事儿之所以又想起来是因为最近有个人联系我，说想做个在线分析系统，正好我觉得Sweave也调顺手了，于是想能否再推进一步，做一点类似于初级产品的东西出来，不仅仅是提交代码运行结果；先把那些八股文的东西先做出来，如果能吸引用户，然后再定向改进（量身定做）。

**Comment by yihui** [comment]
猛然发现： http://netstat.stat.tku.edu.tw/index.php

**Comment by taiyun** [comment]
yixuan做的这个很好啊:)应该开放出来让大家用才是

**Comment by yanping** [comment]
这个很不错  能做不能做？  比如 ggplot2 的那个 http://rweb.stat.ucla.edu/ggplot2/

**Comment by yihui** [comment]
仍然是Shiny，结合一些JS库，问题不大。关键是这个现在对我们有什么用。

**Comment by yanping** [comment]
对我的工作有用

2013/6/8 Yihui Xie notifications@github.com

**Comment by yihui** [comment]
那就用Shiny先走起好了。
