### ISSUE TITLE
在线作图系统

### ISSUE THREAD

**Issue by yihui** [cosname/admin#4]
示例：
http://data.vanderbilt.edu/~graywh/dotplot/

这个应该比整套统计分析系统容易得多。

**Comment by yihui** [comment]
yixuan 4 days ago | link | edit | delete

我觉得这个可以做，而且我个人感觉，目前我们的团队组织、管理较弱，这是短时间内很难有所大的改进的，毕竟大家都是理科出身；但我们也有我们的优势，那就是我们不缺技术，所以在这个过程中我们也应该尽可能发挥我们的长处。作图的这个，本质上前台就是AJAX，后台是PHP，花些时间做做网页的界面应该不是很困难。

**Comment by yihui** [comment]
管理上我们不能一直弱下去。我的目标是复星的核心团队。国家领导人还大多都是理科出身呢：）

等我抽空研究了Webfaction的服务器之后就可以先尝试捣腾一阵了。

**Comment by yihui** [comment]
笔记：Rook包也许有用。

**Comment by yanping** [comment]
这个东西怎么做的 ？@yihui

**Comment by Gwill** [comment]
我看了一下，是这样：

在前端的数据框输入各种数据，然后抛给后端，后端绘图，再更新图片。
- 我们现在的网站架构还无法实现这个功能，只要有全功能的服务器就可以做。
- 不过，现在完全可以使用 js 在前端完全实现，这个绘图功能，所以由后端绘图就显得没有什么意义了。
- 话说回来，这个东西可以归结为 js 图形，这也是现在数据可视化的一个主要技术方向，这方面可以研究一下，但是作为网站功能，却没那么必要了。

**Comment by yihui** [comment]
原来提这个事情本来也与网站无关，只是当时有人在提在线统计分析系统，顺便看到了这个而已。现在再回头来看，用Shiny轻而易举可以实现，没必要考虑了。

**Comment by Gwill** [comment]
我来 close issue。
